kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: micro-applet-management-service # 用户认证服务

steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: package # 流水线名称
    image: maven:3.8.6-openjdk-8
    pull: never
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: maven-cache
        path: /root/.m2 # 将maven下载依赖的目录挂载出来，防止重复下载
      - name: maven-build
        path: /app/docker/mams # 将应用打包好的Jar和执行脚本挂载出来
    commands:
      - $MAVEN_HOME/bin/mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true
      - cd /app/docker/mams
      - chmod +x package.sh
      - sh package.sh

  - name: run # 流水线名称
    image: plugins/docker
    pull: never
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: maven-build
        path: /app/docker/mams # 将应用打包好的Jar和执行脚本挂载出来
      - name: env
        path: /home/mams/.env
      - name: docker
        path: /var/run/docker.sock # 挂载宿主机的docker
    commands:
      - cd /app/docker/mams
      - chmod +x run.sh
      - sh run.sh

volumes: # 定义流水线挂载目录，用于共享数据
  - name: env
    host:
      path: /home/mams/.env
  - name: maven-build
    host:
      path: /app/docker/mams   #jar包目录可以修改从宿主机中挂载的目录
  - name: maven-cache
    host:
      path: /home/asialjim/.m2
  - name: docker
    host:
      path: /var/run/docker.sock
