server:
  port: 10001

knife4j:
  basic:
    enable: true
  setting:
    enable-document-manage: false
    enable-after-script: false
    enable-open-api: false
    enable-footer: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.asialjim.microapplet


spring:
  application:
    name: UserWebDemo
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://192.168.101.200:3306/mams?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:mams}
    password: ${DB_PASSWORD:mams}
  redis:
    host: ${REDIS_HOST:192.168.101.200}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DB:3}
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos_server:192.168.101.200:8848}
        namespace: ${nacos_namespace:public}
        username: ${nacos_username:nacos}
        password: ${nacos_password:nacos}
    loadbalancer:
      retry:
        backoff:
          enabled: true

logging:
  level:
    root: info
    com.asialjim.microapplet.remote.spring: ${REMOTE_SPRING_LOG:info}
