knife4j:
  basic:
    enable: true
  setting:
    enable-document-manage: false
    enable-after-script: false
    enable-open-api: false
    enable-footer: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.asialjim.microapplet




spring:
  application:
    name: User
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DB}

logging:
  level:
    root: info
    com.asialjim.microapplet.remote.spring: ${REMOTE_SPRING_LOG:info}
