server:
  port: ${channel_wx_official_port:80}

knife4j:
  basic:
    enable: true
  setting:
    enable-document-manage: false
    enable-after-script: false
    enable-open-api: false
    enable-footer: false
    enable-group: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  group-configs:
    - group: 'WeChatOfficialChl'
      display-name: 微信公众号渠道
      paths-to-match: '/chl-wx-official/**'
      packages-to-scan: com.asialjim.microapplet.mams.channel.wechat.official.controller

spring:
  datasource:
    driver-class-name: ${mams_db_driver:com.mysql.cj.jdbc.Driver}
    url: ${mams_db_url:jdbc:mysql://192.168.101.200:3306/mams?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${mams_db_username:mams}
    password: ${mams_db_password:mams}
  redis:
    host: ${redis_host:192.168.101.200}
    port: ${redis_port:6379}
    password: ${redis_password}
    database: ${redis_index:3}
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos_server:192.168.101.200:8848}
        namespace: ${nacos_namespace:public}
        username: ${nacos_username:nacos}
        password: ${nacos_password:nacos}
        group: ${nacos_group:DEFAULT_GROUP}
    loadbalancer:
      retry:
        backoff:
          enabled: true

logging:
  level:
    root: info
    com.asialjim.microapplet.remote.spring: ${REMOTE_SPRING_LOG:info}
