server:
  port: ${port:20005}

spring:
  application:
    name: user-fun
    group: fun

  config:
    import:
      - optional:nacos:datasource.yaml
      - optional:nacos:redis.yaml
      - optional:nacos:sensitive.yaml
      - optional:nacos:nacos.yaml?group=remote

  cloud:
    nacos:
      config:
        enabled: true
        server-addr: ${NACOS_URL}
        namespace: ${NACOS_NAMESPACE}
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASSWORD}
        group: ${NACOS_GROUP}
        enable-remote-sync-config: true
        refresh-enabled: true
logging:
  level:
    com:
      asialjim.microapplet.user.infrastructure.repository: DEBUG
      alibaba:
        nacos:
          client:
            naming: error
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
