knife4j:
  basic:
    enable: true
  setting:
    enable-document-manage: false
    enable-after-script: false
    enable-open-api: false
    enable-footer: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: io.github.microapplet


server:
  port: 10001
  servlet:
    context-path: /user/auth

spring:
  application:
    name: User Auth
  datasource:
    driver-class-name: ${MAMS_DB_DRIVER}
    url: ${MAMS_DB_URL}
    username: ${MAMS_DB_USERNAME}
    password: ${MAMS_DB_PASSWORD}
  redis:
    host: ${MAMS_REDIS_HOST}
    port: ${MAMS_REDIS_PORT}
    password: ${MAMS_REDIS_PASSWORD}
    database: ${MAMS_REDIS_DB}

mybatis-flex:
  configuration:
    log-impl: ${MYBATIS_LOG_IMPL:org.apache.ibatis.logging.stdout.StdOutImpl}

logging:
  level:
    root: ${DEFAULT_LOG_LEVEL:info}
