server:
  port: 20004

spring:
  application:
    name: mams-sharing
  threads:
    virtual:
      enabled: true   # 启用虚拟线程
  task:
    scheduling:
      thread-name-prefix: mams-sch-
    execution:
      thread-name-prefix: mams-asy-   # 线程名前缀

  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        group: mams
        file-extension: yaml
        namespace: public
      discovery:
        username: nacos
        password: nacos
        namespace: public
        server-addr: localhost:8848
        group: mams
