knife4j:
  basic:
    enable: true
#  setting:
#    enable-document-manage: false
#    enable-after-script: false
#    enable-open-api: false
#    enable-footer: false
#
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'File'
      paths-to-match: '/file/**'
      packages-to-scan: io.github.microapplet.mams.file.controller


server:
  port: 10002
  servlet:
    context-path: /file

spring:
  application:
    name: File Service
