# Fixed application-dev.properties
spring.cloud.nacos.config.server-addr=172.20.96.1:8848
spring.cloud.nacos.config.namespace=placeex
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=xmm@0127
spring.cloud.nacos.config.group=prd
